name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types:
      - created

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ✨ Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: 🚚 Restore
        run: dotnet restore src

      - name: 🛠️ Build
        run: dotnet build src --configuration Release --no-restore

      - name: 🧪 Test
        run: dotnet test src --configuration Release --no-build

      - name: 📦 Pack
        run: dotnet pack src --configuration Release --no-build

      - name: 🔑 Configure Secrets
        if: github.event_name == 'release'
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}

      - name: 🚀 Deploy Package
        if: github.event_name == 'release'
        run: nuget push "src\Spectrogram\bin\Release\*.nupkg" -SkipDuplicate -Source https://api.nuget.org/v3/index.json
